name: dice
description: A dice rolling app.
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: pacifico
      fonts:
      - asset: fonts/Pacifico-Regular.ttf
    - family: Fasthand
      fonts:
        - asset: fonts/Fasthand-Regular.ttf
